name: C++ CI Benchmark & Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-run:
    name: Build & Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --config Release

      - name: Run Simulation Benchmark (Windows)
        if: runner.os == 'Windows'
        run: .\build\Release\simulacion_benchmark.exe

      - name: Run Simulation Benchmark (Linux)
        if: runner.os == 'Linux'
        run: ./build/simulacion_benchmark
